### ISSUE TITLE
Pfam certification error

### ISSUE THREAD

**Issue by keyuef** [joiningdata/lollipops#57] opened 2022-03-08 11:13 UTC
Hi,
   I try to use the program but can not work. The error shown below:
Get https://pfam.xfam.org/protein/P04637/graphic: x509: certificate signed by unknown authority

Could you give me some advice?
Thanks

**Comment by pbnjay** [comment] 2022-03-10 19:12
Duplicate of #56 - it gives a few options to move forward

**Closed by pbnjay** 2022-03-10 19:12 UTC
